### ISSUE TITLE
Vehicle Changes Colors whenever taking out of garage

### ISSUE THREAD

**Issue by DeputyK9** [Qbox-project/qbx_garages#38]
### Summary

my vehicle changes colors every time I take it out of the the garage

### Reproduction

Error whenever removing vehicle
![image](https://github.com/Qbox-project/qbx_garages/assets/162878658/9ed681ca-1946-4fa5-9e13-1871035d5344)

### Expected behavior

The vehicle should be the same color as when it was places into the garage.

### Actual behavior

Vehicle currently changes colors whenever removed from garage and does not save the color that it was when it was put into the garage.

### Additional context

Only thing edited was in the config and it was the lock default. I just set it from false to true so the vehicle is unlocked when taking it out of the garage. Besides that the only things which I have done that may effect it is that I removed qbx_vehiclekeys and qbx_vehiclefailure.

When asking on discord it was also noted that solareon mentioned "so not sure how you are triggering the garage event but for some reason the data.vehicle isn't being populated"

Discord Forum Post: https://discord.com/channels/1012753553418354748/1216329777380855808

### Current Version

Current

### Custom Resources

None

**Comment by Manason** [comment]
This seems to be working on latest commit after recent PRs.
