### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by EpsilonAETIX** [Qbox-project/qbx_garages#39]
### Summary

Duplication of owned vehicle.

### Reproduction

1. Buy a new vehicle
2. Leave it as it, don't delete
3. Go impound
4. Open impound
5. You'll see your brand new vehicle there
6. Click 'OUT'

There you go, you'll have 2 same vehicles.

### Expected behavior

Shouldn't list the vehicle.

### Actual behavior

It shows the vehicle even though the vehicle status == 'out'. And you can spawn vehicle. 

### Current Version

Latest

### Custom Resources

No, brand new framework.

**Comment by EpsilonAETIX** [comment]
Check `qb-garage:server:GetGarageVehicles`

**Comment by EpsilonAETIX** [comment]
Eyo 💀

**Comment by ArturMichalak** [comment]
Fixed?

**Comment by EpsilonAETIX** [comment]
> Fixed?

Idk, never tested it out.
