### ISSUE TITLE
Job garages duplicate vehicles

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_garages#48]
### Summary

duplicates of same vehicles can be pulled out from job garages

### Reproduction

park a vehicle in job garage
open menu and take out a vehicle
open the menu again and you will see the same vehicle and can pull it out

**Comment by MauroNr1** [comment]
Can confirm.

**Comment by iampitchou** [comment]
Hi, I do have the same issue and fixed it (temporary) by modifying the NetEvent `qb-garage:server:updateVehicleState`

```lua
    if not (config.sharedGarages or owned) then
        exports.qbx_core:Notify(source, Lang:t('error.not_owned'), 'error')
        return
    end
```
