### ISSUE TITLE
Impound vehicle not coming out 

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_garages#49]
### Summary

Impound vehicle not coming out and only getting charged, vehicle doesn't spawn.

### Reproduction

buy a car and /dv or let it despawn, go to impound and try to pullout the vehicle, you will only get charged but the vehicle won't come out.

**Comment by SKITTLE6969** [comment]
should be something to with this 
https://github.com/Qbox-project/qbx_garages/blob/0486349772d399a9ace1030308618fa907f33885/server/main.lua#L100

**Comment by CarlBishop** [comment]
Same issue on my side

**Comment by CarlBishop** [comment]
Did you modified the spawn coords? For my testing it seems the first time I try, the vehicle get spawned somewere (may be underground) and from the second attempt I get the message the vehicle is already out.

**Comment by ArturMichalak** [comment]
Does the error still occur?
