### ISSUE TITLE
Impound and store into garage

### ISSUE THREAD

**Issue by Exu9xx** [Qbox-project/qbx_garages#55]
### Summary

After latest garage update i cannot store vehicle, and impound don't work. Car is impounded and once you try to take it out, it says 'there's no car impounded' takes off money and don't spawn car back.

### Reproduction

1. updated garages to latest version

### Expected behavior

fix it, i dunno

### Actual behavior

That was i told earlier
![image](https://github.com/Qbox-project/qbx_garages/assets/167751974/bfeba910-d8ce-46ec-b245-0570a9fbf699)
![image1](https://github.com/Qbox-project/qbx_garages/assets/167751974/cc60a690-f82e-4348-ac81-463c540cadd9)

### Current Version

1.0.0

### Custom Resources

default qbx garage

**Comment by ArturMichalak** [comment]
Reproduction step too poor

**Comment by ArturMichalak** [comment]
Based on the discord topic. Has the problem been solved?
