### ISSUE TITLE
[Suggestion] sprawn positions list

### ISSUE THREAD

**Issue by ArturMichalak** [Qbox-project/qbx_garages#63]
### The problem

It may be useful to extend the garages with a few spawn areas, as is with qbx_taxijob.
https://github.com/Qbox-project/qbx_taxijob/blob/4ad4a22844088e8ac5b8871940709f91871a6a69/client/main.lua#L469

### Ideal solution

vehicles appear in different places in the parking lot

**Comment by Manason** [comment]
Good suggestion.

**Comment by solareon** [comment]
This should be covered by #71 but if the idea is parking spaces that is something that would need additional work.
