### ISSUE TITLE
After the latest changes to the garage system players are not able to retrieve vehicles from the impound / depot

### ISSUE THREAD

**Issue by BizzleB4** [Qbox-project/qbx_garages#74]
### Summary

Players are not able to retrieve vehicles from the impound / depot. The cash is taken but the vehicle doesn't spawn

### Reproduction

Go to the depot / impound and use the garages to retrieve the vehicle. 

I do receive this error
```
[  script:qbx_garages] SCRIPT ERROR: @qbx_garages/server/spawn-vehicle.lua:29: attempt to index a nil value (field '?')
[  script:qbx_garages] > callbackResponse (@ox_lib/imports/callback/server.lua:79)
[  script:qbx_garages] > handler (@ox_lib/imports/callback/server.lua:96)
[  script:qbx_garages] > rawQuery (@oxmysql/dist/build.js:26467)
[  script:qbx_garages] > processTicksAndRejections (node:internal/process/task_queues:96)
```

Which links to this line of code 
    ```
local netId, veh = qbx.spawnVehicle({ spawnSource = garage.accessPoints[accessPoint].spawn, model = playerVehicle.props.model, props = playerVehicle.props, warp = warpPed})
    ```

### Expected behavior

For the vehicle to spawn after paying the fee

### Actual behavior

Vehicle did not spawn

### Current Version

version '1.0.0' -- Latest 

### Custom Resources

No

**Comment by solareon** [comment]
Have you updated your config to match the new changes?

**Comment by BizzleB4** [comment]
> Have you updated your config to match the new changes?

I've installed a fresh version of both qbx_vehicles and qbx_garages

**Comment by solareon** [comment]
Please try the fix in #75 @BizzleB4

**Comment by BizzleB4** [comment]
Testing it now @solareon

**Comment by BizzleB4** [comment]
The issue has been fixed! @solareon
